
// Maps English levels to their corresponding topics
export const topicsByLevel: Record<string, string[]> = {
  "0": [
    "Normal sentence structure",
    "A/an",
    "Plurals",
    "Personal pronouns",
    "Verb To be",
    "This/that/these/those",
    "There is/ there are",
    "Possessive pronouns",
    "Can",
    "Imperative",
    "Have/have got",
    "Present simple",
    "Present continuous",
    "Present simple vs present continuous",
    "Preposition of place",
    "Preposition of time",
    "Special questions",
    "How much/how many",
    "Some/any",
    "\"Ing\" form – To infinitive",
    "Reading" // Added reading topic
  ],
  "1": [
    "Plurals/Countable-Uncountable",
    "Subject pronouns/ To be",
    "Article(a/an/the)/ This/that/these/those",
    "Have got – Can",
    "Possessive case (adjective and pronoun)",
    "Present Continuous",
    "Object pronouns/The Imperative",
    "There is/are – some/any/no",
    "Present Simple (Simple vs Continuous)",
    "A lot of- much-many- a little-a few",
    "Past Simple (Was/were-had)",
    "Past Simple (Regular/Irregular verbs)",
    "Present Perfect (Past Simple vs Present Perfect)",
    "Prepositions (Time-Place-Movement)",
    "The Future (Will-be going to- Present Continuous)",
    "Adjective/Adverbs/Comparison",
    "Questions (Subject/Object questions- Question Tags)",
    "Modal verbs (can/could/may/must/needn't/shall/will)",
    "Infinitive/Gerund/Too/Enough",
    "Both/Neither/All/None",
    "Reading" // Added reading topic
  ],
  "2": [
    "Present Simple/ Continuous/Stative verb",
    "Past Simple/Continuous/Used to",
    "Present Perfect Simple/ Present Perfect Continuous",
    "Past Perfect Simple/ Past Perfect Continuous",
    "Future time (present con/will/going to/present simple)",
    "Prepositions of time and place",
    "The Passive 1",
    "The Passive 2",
    "Countable and uncountable nouns",
    "Articles",
    "Pronouns and possessive determiners",
    "Relative clause",
    "Modals: ability, permission, advice",
    "Modals: obligation, probability, possibility",
    "Reading" // Added reading topic
  ],
  "3": [
    "Modals 3: Modal perfect",
    "Questions, question tags, indirect questions",
    "So and such, too and enough",
    "Comparative and Superlative",
    "Conditionals (zero, first, second)",
    "Conditionals (third and mixed)",
    "Reported Speech",
    "Reported questions, orders, requests",
    "Direct and indirect objects",
    "Wish",
    "Ing and infinitive",
    "Both, either, neither, so nor",
    "Connectives",
    "The causative",
    "Reading" // Added reading topic
  ],
  "4": [
    "First week",
    "Second week",
    "Third week",
    "Fourth week",
    "Fifth week",
    "Sixth week",
    "Seventh week",
    "Eighth week",
    "Ninth week",
    "Tenth week",
    "Eleventh week"
  ],
  "IELTS": [
    "First week",
    "Second week",
    "Third week",
    "Fourth week",
    "Fifth week",
    "Sixth week",
    "Seventh week",
    "Eighth week",
    "Ninth week",
    "Tenth week",
    "Eleventh week"
  ]
};
